### ISSUE TITLE
Šrifto dydis aprašymuose

### ISSUE THREAD

**Issue by Wincikas** [karina-klinkeviciute/humanrightsindex#3]
![Image](https://github.com/user-attachments/assets/5080f9e0-2b4a-4a4c-8bd5-c32f624f185e)

Labai mažos raidės kur tekstas (..This survey allows you to see your personal social vulnerability score. You have three options: You can create a group, join a group or do the survey individually...), visomis kalbomis

Telefone daug maž ok. Bet jei šiek tiek padidės 1-2 punktais šriftas gal neišdarkys

**Comment by karina-klinkeviciute** [comment]
Šiek tiek padidinau. Bet dabar telefone man atrodo per mažas. Padidinti telefone?
