### ISSUE TITLE
Mygtukai užlipa ant pagrindinio pavadinimo

### ISSUE THREAD

**Issue by Wincikas** [karina-klinkeviciute/humanrightsindex#7]
Apie projektą mygtukas telefonuose užlipa ant pavadinimo.
Galbūt įmanoma telefonuose pažeminti:
![Image](https://github.com/user-attachments/assets/fcbdf39d-9306-4177-9576-74c114df8580)

**Comment by karina-klinkeviciute** [comment]
Sutrumpinau kalbos pasirinkimą ir dabar telpa. Ir pats pasirinkimas dabar gražiau atrodo. Ar taip tiks?
